services:
  go-whatsapp-multidevice-rest:
    build:
      context: .
      platform: linux/arm64
      dockerfile: ./Dockerfile      
    image: 'dimaskiddo/go-whatsapp-multidevice-rest:latest'
    env_file:
      - ./.env
    volumes:
      - ./dbs:/usr/app/go-whatsapp-multidevice-rest/dbs
